### ISSUE TITLE
just an issue

### ISSUE THREAD

**Issue by kyoobey** [kyoobey/azalea#1]
hi @mat-1 i wanted to contact you but couldn't find your socials on your website so i had to resort to this instead

i watched liveoverflow's minecraft series recently and wanted to check out his server and play minecraft for the first time so i scanned a few ips and i think i probably got it (two ips, both pointing to the same server, one ending with _redacted_ and the other ending with _redacted_) but i can't get in because it's always full, is this a honeypot and there is another server somewhere else? or perhaps is this some sort of challenge to kick out other players and enter the server? if possible can you confirm?

**Comment by kyoobey** [comment]
also, what's up with those N00bBot accounts?

**Comment by cleonyc** [comment]
:/

**Comment by mat-1** [comment]
There's only one correct IP, the others are honeypots. The server is always full with the n00bbot accounts because someone decided to fill up the server with bots "to prevent griefers".

**Comment by Shrecknt** [comment]
Anyone gonna close this issue?
I don't think there's any changes that need to be done to azalea
